"""
Agent 8: REPORT GENERATION AGENT
Generates structured AI radiology reports in JSON, PDF, and HTML formats.
Includes findings, confidence scores, explainability, and measurements.
"""
from __future__ import annotations

import json
import logging
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


@dataclass
class Measurement:
    label: str
    value: float
    unit: str
    location: Optional[str] = None


@dataclass
class Finding:
    description: str
    severity: str  # "normal" | "mild" | "moderate" | "severe" | "critical"
    confidence: float
    location: Optional[str] = None
    measurement: Optional[Measurement] = None


@dataclass
class AIReport:
    report_id: str
    study_id: str
    patient_pseudo_id: str
    study_date: Optional[str]
    modality: str
    body_part: Optional[str]
    model_name: str
    model_version: str
    task: str
    top_prediction: str
    overall_confidence: float
    findings: List[Finding]
    measurements: List[Measurement]
    clinical_summary: str
    clinical_explanation: str
    heatmap_path: Optional[str]
    overlay_path: Optional[str]
    preprocessing_config: Optional[Dict[str, Any]]
    generated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    disclaimer: str = (
        "This report is generated by AutoRadixAI and is intended to assist, "
        "not replace, clinical judgment. All findings must be verified by a "
        "qualified radiologist before clinical use."
    )


class ReportGenerationAgent:
    """
    Generates structured AI radiology reports.
    Outputs: JSON, HTML, PDF (via WeasyPrint or pdfkit).
    """

    def __init__(self, output_dir: Path) -> None:
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def generate_report(
        self,
        report_data: AIReport,
        formats: Optional[List[str]] = None,
    ) -> Dict[str, Optional[str]]:
        """
        Generate report in requested formats.
        Returns dict mapping format → file path.
        """
        formats = formats or ["json", "html"]
        paths: Dict[str, Optional[str]] = {}

        if "json" in formats:
            paths["json"] = await self._save_json(report_data)
        if "html" in formats:
            paths["html"] = await self._save_html(report_data)
        if "pdf" in formats:
            paths["pdf"] = await self._save_pdf(report_data, paths.get("html"))

        logger.info(
            "Report generated for study=%s, formats=%s",
            report_data.study_id,
            list(paths.keys()),
        )
        return paths

    # ------------------------------------------------------------------
    # Format writers
    # ------------------------------------------------------------------

    async def _save_json(self, report: AIReport) -> str:
        path = self.output_dir / f"{report.report_id}.json"
        data = asdict(report)
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(data, fh, indent=2, default=str)
        return str(path)

    async def _save_html(self, report: AIReport) -> str:
        html = self._render_html(report)
        path = self.output_dir / f"{report.report_id}.html"
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(html)
        return str(path)

    async def _save_pdf(
        self, report: AIReport, html_path: Optional[str]
    ) -> Optional[str]:
        """Convert HTML to PDF using WeasyPrint if available."""
        pdf_path = self.output_dir / f"{report.report_id}.pdf"
        try:
            from weasyprint import HTML as WeasyHTML  # type: ignore
            if html_path:
                WeasyHTML(filename=html_path).write_pdf(str(pdf_path))
                return str(pdf_path)
        except ImportError:
            logger.warning("WeasyPrint not installed; PDF export skipped.")
        except Exception as exc:
            logger.error("PDF generation failed: %s", exc)
        return None

    # ------------------------------------------------------------------
    # HTML template
    # ------------------------------------------------------------------

    def _render_html(self, r: AIReport) -> str:
        severity_colors = {
            "normal": "#22c55e",
            "mild": "#f59e0b",
            "moderate": "#f97316",
            "severe": "#ef4444",
            "critical": "#991b1b",
        }

        findings_html = ""
        for f in r.findings:
            color = severity_colors.get(f.severity, "#6b7280")
            measurement_html = ""
            if f.measurement:
                measurement_html = (
                    f'<span class="measurement">'
                    f'{f.measurement.value} {f.measurement.unit}'
                    f"</span>"
                )
            findings_html += f"""
            <div class="finding">
                <span class="badge" style="background:{color}">{f.severity.upper()}</span>
                <span class="finding-text">{f.description}</span>
                {measurement_html}
                <span class="confidence">Confidence: {f.confidence*100:.1f}%</span>
            </div>"""

        overlay_html = ""
        if r.overlay_path:
            overlay_html = f'<img src="{r.overlay_path}" alt="AI Heatmap Overlay" class="heatmap-img"/>'

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>AutoRadixAI Report — {r.report_id}</title>
  <style>
    :root {{ --primary: #1e40af; --bg: #f8fafc; }}
    body {{ font-family: 'Segoe UI', sans-serif; background: var(--bg); color: #1e293b; margin: 0; padding: 2rem; }}
    .header {{ background: var(--primary); color: white; padding: 1.5rem 2rem; border-radius: 0.75rem; margin-bottom: 1.5rem; }}
    .header h1 {{ margin: 0; font-size: 1.5rem; }}
    .header .subtitle {{ opacity: 0.8; font-size: 0.9rem; margin-top: 0.25rem; }}
    .card {{ background: white; border-radius: 0.75rem; padding: 1.5rem; margin-bottom: 1rem; box-shadow: 0 1px 3px rgba(0,0,0,.1); }}
    .card h2 {{ margin: 0 0 1rem; font-size: 1.1rem; color: var(--primary); border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5rem; }}
    .meta-grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 0.75rem; }}
    .meta-item label {{ font-size: 0.75rem; color: #64748b; display: block; text-transform: uppercase; letter-spacing: .05em; }}
    .meta-item span {{ font-weight: 600; font-size: 0.95rem; }}
    .confidence-bar {{ background: #e2e8f0; border-radius: 9999px; height: 8px; margin-top: 0.5rem; }}
    .confidence-fill {{ height: 100%; border-radius: 9999px; background: var(--primary); }}
    .finding {{ padding: 0.75rem; background: #f8fafc; border-left: 4px solid #e2e8f0; margin-bottom: 0.5rem; border-radius: 0 0.5rem 0.5rem 0; display: flex; align-items: center; gap: 0.75rem; }}
    .badge {{ padding: 0.2rem 0.6rem; border-radius: 9999px; color: white; font-size: 0.7rem; font-weight: 700; }}
    .finding-text {{ flex: 1; }}
    .measurement {{ font-size: 0.85rem; color: #475569; }}
    .confidence {{ font-size: 0.8rem; color: #64748b; }}
    .heatmap-img {{ max-width: 100%; border-radius: 0.5rem; border: 1px solid #e2e8f0; }}
    .disclaimer {{ background: #fef9c3; border: 1px solid #fde047; border-radius: 0.5rem; padding: 1rem; font-size: 0.85rem; color: #713f12; }}
    .summary {{ line-height: 1.7; color: #334155; }}
  </style>
</head>
<body>
  <div class="header">
    <h1>AutoRadixAI — Radiology Intelligence Report</h1>
    <div class="subtitle">Report ID: {r.report_id} | Generated: {r.generated_at}</div>
  </div>

  <div class="card">
    <h2>Study Information</h2>
    <div class="meta-grid">
      <div class="meta-item"><label>Patient (Pseudo ID)</label><span>{r.patient_pseudo_id}</span></div>
      <div class="meta-item"><label>Modality</label><span>{r.modality}</span></div>
      <div class="meta-item"><label>Body Part</label><span>{r.body_part or "—"}</span></div>
      <div class="meta-item"><label>Study Date</label><span>{r.study_date or "—"}</span></div>
      <div class="meta-item"><label>AI Model</label><span>{r.model_name} v{r.model_version}</span></div>
      <div class="meta-item"><label>Task</label><span>{r.task}</span></div>
    </div>
  </div>

  <div class="card">
    <h2>AI Prediction</h2>
    <div class="meta-grid">
      <div class="meta-item">
        <label>Top Prediction</label>
        <span>{r.top_prediction}</span>
      </div>
      <div class="meta-item">
        <label>Confidence</label>
        <span>{r.overall_confidence*100:.1f}%</span>
        <div class="confidence-bar">
          <div class="confidence-fill" style="width:{r.overall_confidence*100:.1f}%"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="card">
    <h2>Findings</h2>
    {findings_html if findings_html else '<p style="color:#64748b">No specific findings recorded.</p>'}
  </div>

  <div class="card">
    <h2>Clinical Summary</h2>
    <p class="summary">{r.clinical_summary}</p>
  </div>

  <div class="card">
    <h2>AI Explainability</h2>
    <p class="summary">{r.clinical_explanation}</p>
    {overlay_html}
  </div>

  <div class="card">
    <div class="disclaimer">⚠ {r.disclaimer}</div>
  </div>
</body>
</html>"""
